<!-- Nuvei - Reload and empty customerData cart -->
<script>
    window.addEventListener('load', function () {
        require([
            'Magento_Customer/js/customer-data',
            'domReady!'
        ], function (customerData) {
            var sections = ['cart'];
            customerData.initStorage();
            customerData.invalidate(sections);
            customerData.reload(sections, true);
        });
    });
</script>
<!--/ Nuvei - Reload and empty customerData cart -->